# Generated by Django 5.1.3 on 2024-11-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(to='music.genre'),
        ),
    ]
